In [12]:
from problem import *

def build_maze():
    maze = [[0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
            [0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0],
            [0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0],
            [0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
            [1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0],
            [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
            [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
            [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
            [0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0],
            [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1],
            [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
            [0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0],
            [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
            [0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
            [0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0],
            [1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
            [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0],
            [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0]]
    start = [0, 5]
    destination = [15, 19]
    return maze, start, destination

In [13]:
import numpy as np


def build_graph(maze, start, destination):
    """ Build a graph in adjacency list representation

        You should assign the vertex index for each path (i, j) in the ascending order
        of the number 100 * i + j. For example, if there exists only two paths in the 
        maze with coordinates (10, 10) and (10, 11). The path (10, 10) has the index 0. 
        The other one has the index 1.

    Args:
        maze (list): maze values represents whether there is a path (1) or not (0)
        start (list): a start coordinate
        destination (list): a destination coordinate

    Returns:
        graph (list): an adjacency list representation of maze graph
        start (int): a start vertex index
        destination (int): a destinatnon vertex index

    """
    rows, cols = len(maze), len(maze[0])
    graph = {}
    vertex_index = {}
    index_counter = 0

    def get_index(i, j):
        return 100 * i + j

    def add_edge(u, v):
        if u not in graph:
            graph[u] = []
        graph[u].append(v)
        
    for i in range(rows):
        for j in range(cols):
            if maze[i][j] == 1:
                current_index = get_index(i, j)
                vertex_index[(i, j)] = current_index
                
                neighbors = [(i + 1, j), (i - 1, j), (i, j + 1), (i, j - 1)]
                for neighbor in neighbors:
                    ni, nj = neighbor
                    if 0 <= ni < rows and 0 <= nj < cols and maze[ni][nj] == 1:
                        neighbor_index = get_index(ni, nj)
                        add_edge(current_index, neighbor_index)

    start = vertex_index[tuple(start)]
    destination = vertex_index[tuple(destination)]

    return graph, start, destination

In [3]:
def dfs(graph, start, destination):
    """ Find destination node using a depth first search (DFS) algorithm
        
        DFS should halt when it visits the destination vertex. 
        DFS should determine the next visit vertex in ascending order of vertex indices. 
        For example, if dfs currently visits the vertex 6 whose neighbors are 9, 3, 20, 
        then the next visited vertex will be 3.

    Args:
        graph (list): an adjacency list representation of maze graph
        start (int): a start vertex index
        destination (int): a destinatnon vertex index

    Returns:
        success (bool): True if visits the destination vertex. False otherwise
        history (list): the vertex indices in visiting order
    """
    stack = [start]
    visited = set()
    history = []

    while stack:
        current_vertex = stack.pop()
        history.append(current_vertex)

        if current_vertex == destination:
            return True, history

        if current_vertex not in visited:
            visited.add(current_vertex)
            neighbors = sorted(graph.get(current_vertex, []))
            stack.extend(neighbors)

    return False, history

In [4]:
from collections import deque

def bfs(graph, start, destination):
    """ Find destination node using a breadth first search (BFS) algorithm.
        
    Args:
        graph (list): an adjacency list representation of maze graph
        start (int): a start vertex index
        destination (int): a destinatnon vertex index

    Returns:
        success (bool): True if visits the destination vertex. False otherwise
        history (list): the vertex indices in visiting order
    """
    visited = set() 
    queue = deque([start]) 
    history = [] 

    while queue:
        current_vertex = queue.popleft()
        history.append(current_vertex)

        if current_vertex == destination:
            return True, history 

        visited.add(current_vertex)

        for neighbor in graph.get(current_vertex, []):
            if neighbor not in visited:
                queue.append(neighbor)

    return False, history


In [5]:
import heapq

def astar(graph, start, destination):
    """ Find destination node using a A* algorithm.

    Args:
        graph (list): an adjacency list representation of maze graph
        start (int): a start vertex index
        destination (int): a destinatnon vertex index

    Returns:
        success (bool): True if visits the destination vertex. False otherwise
        history (list): the vertex indices in visiting order
    """
    def heuristic(node, destination): # 맨해튼 거리 함수
        return abs(node // 100 - destination // 100) + abs(node % 100 - destination % 100) 

    priority_queue = [(heuristic(start, destination), 0, start)]
    heapq.heapify(priority_queue)

    # 방문 노드랑 비용
    visited = {start: 0}
    
    history = []

    while priority_queue:
        _, cost, current_node = heapq.heappop(priority_queue)
        
        if current_node == destination:
            return True, history + [current_node]

        for neighbor in graph.get(current_node, []):
            new_cost = cost + 1  
            if neighbor not in visited or new_cost < visited[neighbor]:
                visited[neighbor] = new_cost
                heapq.heappush(priority_queue, (new_cost + heuristic(neighbor, destination), new_cost, neighbor))

        history.append(current_node)

    return False, history

In [6]:
maze, start_coordinate, destination_coordinate = build_maze()
graph, start_index, destination_index = build_graph(maze, start_coordinate, destination_coordinate)
    
dfs_success, dfs_history = dfs(graph, start_index, destination_index)
bfs_success, bfs_history = bfs(graph, start_index, destination_index)
astar_success, astar_history = astar(graph, start_index, destination_index)

In [7]:
np.array(dfs_history)

array([   5,  105,  205,  305,  405,  505,  605,  705,  805,  905,  906,
        907, 1007, 1107, 1207, 1208, 1209, 1210, 1310, 1410, 1510, 1610,
       1710, 1810, 1910, 1810, 1710, 1610, 1510, 1511, 1512, 1513, 1613,
       1713, 1714, 1715, 1815, 1915, 1815, 1715, 1716, 1717, 1718, 1818,
       1718, 1717, 1716, 1715, 1714, 1615, 1715, 1515, 1615, 1516, 1517,
       1518, 1519])

In [8]:
np.array(bfs_history)

array([   5,  105,  205,  305,  405,  505,  605,  705,  805,  704,  905,
        703,  906,  904,  603,  702,  907,  903,  503,  701, 1007, 1003,
        403,  700, 1107, 1103,  303,  402, 1207, 1203,  203,  401, 1208,
       1303,  103,  301,  400, 1209, 1403, 1302,  201, 1210, 1503, 1301,
        101, 1310, 1110, 1211, 1603, 1504, 1401, 1300,    1, 1410, 1010,
       1212, 1703, 1505, 1501, 1510,  910, 1213, 1803, 1605, 1601, 1610,
       1511,  810, 1214, 1903, 1705, 1701, 1710, 1512,  811, 1215, 1706,
       1700, 1810, 1513,  711,  812, 1115, 1707, 1910, 1613,  611,  813,
       1015, 1807, 1713,  511,  814, 1014, 1907, 1714,  411,  512,  815,
       1013, 1715,  410,  513,  816, 1815, 1615, 1716,  409,  514,  817,
       1915, 1515, 1717,  309,  414,  917,  717, 1516, 1718,  209,  415,
       1017,  617, 1517, 1818,  109,  210,  315, 1018,  618, 1518,    9,
        211,  316, 1019,  619, 1418, 1519])

In [9]:
np.array(astar_history)

array([   5,  105,  205,  305,  405,  505,  605,  705,  805,  905,  906,
        907, 1007, 1107, 1207, 1208, 1209, 1210, 1211, 1310, 1212, 1410,
       1213, 1510, 1214, 1511, 1215, 1512, 1513,  704,  904, 1110, 1610,
       1115, 1613,  703,  903, 1003, 1103, 1203, 1303, 1403, 1503, 1504,
       1010, 1505, 1710, 1015, 1713, 1714, 1715, 1615, 1716, 1515, 1717,
       1516, 1718, 1517, 1518, 1519])

In [10]:
len(dfs_history)

57

In [14]:
!python main.py